microScheme: hashtablemap< Key, T >::base_iterator< value_T, map_T > Class Template Reference
hashtablemap< Key, T >::base_iterator< value_T, map_T > Class Template Reference
#include <hashtablemap.hpp>
Public Types
typedef std::input_iterator_tag forward_iterator
typedef value_T value_type
typedef map_T map_type
typedef difference_type difference_type
typedef pointer pointer
typedef reference reference
Public Member Functions
base_iterator ()
base_iterator (unsigned long my_index, _value_iterator my_value_it, map_type *my_map)
base_iterator (const base_iterator &it)
base_iterator & operator= (const base_iterator &it)
bool operator== (const base_iterator &it) const
bool operator!= (const base_iterator &it) const
reference operator* ()
pointer operator-> () const
base_iterator & operator++ ()
base_iterator operator++ (int)
Private Attributes
map_type * map_m
unsigned long index_m
_value_iterator value_it_m
Friends
class hashtablemap
Member Typedef Documentation
template<class Key, class T> template<typename value_T , typename map_T > typedef difference_type hashtablemap< Key, T >::base_iterator< value_T, map_T >::difference_type
template<class Key, class T> template<typename value_T , typename map_T > typedef std::input_iterator_tag hashtablemap< Key, T >::base_iterator< value_T, map_T >::forward_iterator
template<class Key, class T> template<typename value_T , typename map_T > typedef map_T hashtablemap< Key, T >::base_iterator< value_T, map_T >::map_type
template<class Key, class T> template<typename value_T , typename map_T > typedef pointer hashtablemap< Key, T >::base_iterator< value_T, map_T >::pointer
template<class Key, class T> template<typename value_T , typename map_T > typedef reference hashtablemap< Key, T >::base_iterator< value_T, map_T >::reference
template<class Key, class T> template<typename value_T , typename map_T > typedef value_T hashtablemap< Key, T >::base_iterator< value_T, map_T >::value_type
Constructor & Destructor Documentation
template<class Key, class T> template<typename value_T , typename map_T > hashtablemap< Key, T >::base_iterator< value_T, map_T >::base_iterator () inline
Referenced by hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator++().
template<class Key, class T> template<typename value_T , typename map_T > hashtablemap< Key, T >::base_iterator< value_T, map_T >::base_iterator (unsigned long my_index, _value_iterator my_value_it, map_type * my_map) inline
template<class Key, class T> template<typename value_T , typename map_T > hashtablemap< Key, T >::base_iterator< value_T, map_T >::base_iterator (const base_iterator< value_T, map_T > & it) inline
Member Function Documentation
template<class Key, class T> template<typename value_T , typename map_T > bool hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator!= (const base_iterator< value_T, map_T > & it) const inline
References hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator==().
template<class Key, class T> template<typename value_T , typename map_T > reference hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator* () inline
References hashtablemap< Key, T >::base_iterator< value_T, map_T >::value_it_m.
template<class Key, class T> template<typename value_T , typename map_T > base_iterator& hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator++ () inline
References hashtablemap< Key, T >::base_iterator< value_T, map_T >::base_iterator(), hashtablemap< Key, T >::begin(), hashtablemap< Key, T >::end(), hashtablemap< Key, T >::base_iterator< value_T, map_T >::index_m, hashtablemap< Key, T >::base_iterator< value_T, map_T >::map_m, and hashtablemap< Key, T >::base_iterator< value_T, map_T >::value_it_m.
template<class Key, class T> template<typename value_T , typename map_T > base_iterator hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator++ (int) inline
template<class Key, class T> template<typename value_T , typename map_T > pointer hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator-> () const inline
template<class Key, class T> template<typename value_T , typename map_T > base_iterator& hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator= (const base_iterator< value_T, map_T > & it) inline
References hashtablemap< Key, T >::base_iterator< value_T, map_T >::index_m, hashtablemap< Key, T >::base_iterator< value_T, map_T >::map_m, and hashtablemap< Key, T >::base_iterator< value_T, map_T >::value_it_m.
template<class Key, class T> template<typename value_T , typename map_T > bool hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator== (const base_iterator< value_T, map_T > & it) const inline
References hashtablemap< Key, T >::base_iterator< value_T, map_T >::index_m, and hashtablemap< Key, T >::base_iterator< value_T, map_T >::value_it_m.
Referenced by hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator!=().
Friends And Related Function Documentation
template<class Key, class T> template<typename value_T , typename map_T > friend class hashtablemap friend
Member Data Documentation
template<class Key, class T> template<typename value_T , typename map_T > unsigned long hashtablemap< Key, T >::base_iterator< value_T, map_T >::index_m private
Referenced by hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator++(), hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator=(), and hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator==().
template<class Key, class T> template<typename value_T , typename map_T > map_type* hashtablemap< Key, T >::base_iterator< value_T, map_T >::map_m private
Referenced by hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator++(), and hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator=().
template<class Key, class T> template<typename value_T , typename map_T > _value_iterator hashtablemap< Key, T >::base_iterator< value_T, map_T >::value_it_m private
Referenced by hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator*(), hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator++(), hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator=(), and hashtablemap< Key, T >::base_iterator< value_T, map_T >::operator==().
The documentation for this class was generated from the following file:
hashtablemap.hpp